const SET_USER: 'SET_USER' = 'SET_USER';
const SET_COURSES: 'SET_COURSES' = 'SET_COURSES';
const CLEAR_LOAD: 'CLEAR_LOAD' = 'CLEAR_LOAD';
const SET_LOAD: 'SET_LOAD' = 'SET_LOAD';

export {
  SET_USER,
  SET_COURSES,
  CLEAR_LOAD,
  SET_LOAD
};
