// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'button': string;
  'button__container': string;
  'display': string;
  'hide': string;
  'lession': string;
  'lession__title': string;
  'lessions': string;
  'slideInAside': string;
  'slideOutAside': string;
  'title': string;
  'word': string;
  'word__display': string;
  'words': string;
}
export const cssExports: CssExports;
export default cssExports;
