// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'course': string;
  'course__arrowLeft': string;
  'course__arrowRight': string;
  'course__bar': string;
  'course__buttonPlay': string;
  'course__buttons': string;
  'course__container': string;
  'course__content': string;
  'course__feedback': string;
  'course__image': string;
  'course__link': string;
  'course__message': string;
  'course__modalButton': string;
  'course__playText': string;
  'course__progress': string;
  'course__pronunciation': string;
  'course__result': string;
  'course__slideshow': string;
  'course__slideshowWord': string;
  'course__titleEnglish': string;
  'course__titleSpanish': string;
  'course__vocabularies': string;
  'course__word': string;
  'course__wordEnglish': string;
  'course__wordLesson': string;
  'course__wordSpanish': string;
}
export const cssExports: CssExports;
export default cssExports;
