// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__button': string;
  'form__field': string;
  'form__label': string;
  'table': string;
  'table__actionAdd': string;
  'table__actionEdit': string;
  'table__tbodyTd': string;
  'table__tbodyTr': string;
}
export const cssExports: CssExports;
export default cssExports;
