// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'course': string;
  'course__button': string;
  'course__button_container': string;
  'course__container': string;
  'course__description': string;
  'course__invalid': string;
  'course__item': string;
  'course__items': string;
  'course__picture': string;
  'course__progress': string;
  'course__progress_container': string;
  'course__progress_status': string;
  'course__progress_value': string;
  'course__title': string;
}
export const cssExports: CssExports;
export default cssExports;
