// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button__container': string;
  'course': string;
  'course__invalid': string;
  'description': string;
  'item': string;
  'items': string;
  'progress': string;
  'progress__container': string;
  'progress__status': string;
  'progress__value': string;
}
export const cssExports: CssExports;
export default cssExports;
