// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'profile': string;
  'profile__bio': string;
  'profile__details': string;
  'profile__info': string;
  'profile__name': string;
  'profile__picture': string;
}
export const cssExports: CssExports;
export default cssExports;
