// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'admin': string;
  'admin__header': string;
  'table': string;
  'table__actionAdd': string;
  'table__actionEdit': string;
  'table__tbodyTd': string;
  'table__tbodyTr': string;
  'table__theadTh': string;
}
export const cssExports: CssExports;
export default cssExports;
