// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navigator': string;
  'navigator__hamburger': string;
  'navigator__line': string;
  'navigator__link': string;
  'navigator__link_container': string;
  'navigator__links': string;
  'navigator__open': string;
}
export const cssExports: CssExports;
export default cssExports;
